### ISSUE TITLE
Whitescreen on macOS

### ISSUE THREAD

**Issue by iojanis** [zsmatrix62/echoo-app#12]
Tauris web view  doesn't show anything on macOS. 
<img width="912" alt="Screenshot 2022-04-25 at 14 12 10" src="https://user-images.githubusercontent.com/12971934/165086568-86b9cff1-532c-46ca-b652-c317df00985c.png">

**Comment by zsmatrix62** [comment]
hi. Fixed this issue in [v0.26.1](https://github.com/zsmatrix62/echoo-app/releases/tag/v0.26.1)

**Comment by marco-gallegos** [comment]
this issue persist on this version (0.26.1) on mac monterrey

**Comment by zsmatrix62** [comment]
> this issue persist on this version (0.26.1) on mac monterrey

Im also on Mac monterrey and everything seems good, can you give more detail?

**Comment by marco-gallegos** [comment]
> > this issue persist on this version (0.26.1) on mac monterrey
> 
> Im also on Mac monterrey and everything seems good, can you give more detail?

for now only download the dmg from releases to install it and see this white screen bug is my experience.

![image](https://user-images.githubusercontent.com/6290032/168409445-15283970-e955-4171-848e-210a35d800c3.png)

i leave here my mac os details please tell me which info is useful for you.

**Comment by zsmatrix62** [comment]
> > > this issue persist on this version (0.26.1) on mac monterrey
> > 
> > 
> > Im also on Mac monterrey and everything seems good, can you give more detail?
> 
> for now only download the dmg from releases to install it and see this white screen bug is my experience.
> 
> ![image](https://user-images.githubusercontent.com/6290032/168409445-15283970-e955-4171-848e-210a35d800c3.png)
> 
> i leave here my mac os details please tell me which info is useful for you.

Thanks, I see this ... when I was building on my machine it's good, but in release page it's from Github's action, I will check it and see how to solve.

**Comment by zsmatrix62** [comment]
@marco-gallegos  @iojanis shall fixed now in release [v0.26.2](https://github.com/zsmatrix62/echoo-app/releases/tag/v0.26.2)

**Comment by marco-gallegos** [comment]
yep, solved at least on mac monterrey
